### ISSUE TITLE
Website Milestone Tasks 

### ISSUE THREAD

**Issue by anaboccanfuso** [SCCapstone/Appstone#452]
- [ ] styling
- [ ] embed video
- [ ] text explaining how/why to use our app
- [ ] images: screenshots of our app (at least 3)
- [ ] about page: listing names, linking to linkedin
- [ ] link to github repo

**Comment by alliescott** [comment]
https://github.com/SCCapstone/Appstone/commit/a9a3f3fa7379d23e53d6100da4113e82232bd4f7 created about us page, embedded PoC demo, linked to github repo, added descriptions of us

**Comment by alliescott** [comment]
maybe we should make the "About the Creators" text a button that links to another page with just our information cut and pasted over? since in the description it says its a different page?

**Comment by alliescott** [comment]
we need to have the "about the creators" link also in the "about flashdash" page. we only turn in /about-us url and that url needs to link to /people
